# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yeelightcli < Formula
  desc "Command-line tool for managing Yeelight devices. Right now it supports 95% of all features presented in the official documentation."
  homepage "https://github.com/oherych/yeelightcli"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oherych/yeelightcli/releases/download/v1.2.2/yeelightcli_1.2.2_Darwin_x86_64.tar.gz"
      sha256 "92758f9412bb6779042371615d758ed7d8ce9d71eb2d3695b62eda4b96944939"

      def install
        bin.install "yeelightcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oherych/yeelightcli/releases/download/v1.2.2/yeelightcli_1.2.2_Darwin_arm64.tar.gz"
      sha256 "4c9b5af5365728ad1d044d92431e26d87a3c2f193d74fe62c922d610aeffe07d"

      def install
        bin.install "yeelightcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/oherych/yeelightcli/releases/download/v1.2.2/yeelightcli_1.2.2_Linux_x86_64.tar.gz"
      sha256 "30e17162d51d329d728b81c0b1b9c31a505756a40a8ff49fba4cb18ef2cc67df"

      def install
        bin.install "yeelightcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oherych/yeelightcli/releases/download/v1.2.2/yeelightcli_1.2.2_Linux_arm64.tar.gz"
      sha256 "ab91a5fcdc9edbbc744fceb23987636ce800225aea1e33380200cb3cace018be"

      def install
        bin.install "yeelightcli"
      end
    end
  end

  test do
    system "#{bin}/yeelightcli"
  end
end
